### ISSUE TITLE
Imported mesh's submeshes getting reordered

### ISSUE THREAD

**Issue by 86maylin** [WolvenKit/WolvenKit#1036]
**Describe the bug**
If you merge submeshes in blender and then separate them either via selection or via material, even tho you rename the submesh names correctly, upon import the order of the submeshes will get reordered randomly so material will not be linked correctly. I also tried the "keep submesh order" option in import, but I got an exception when trying to do mesh preview which may be related to this bug: https://github.com/WolvenKit/WolvenKit/issues/1035

**To Reproduce**
1. I exported this mesh "t2_119_pma_jacket__suit" to blender
2. Either assign individual materials to the submeshes, merge them and then separate by material
Or, merge them all and separate by selection
3. Rename the submeshes to their correct names(so the order is correct) and export
4. Import the mesh
5. submeshes will be reordered (can check via mesh preview)

**Expected behavior**
It should keep the correct submesh order so that material can be mapped correctly. I'd like to merge submeshes because I can use sculpt mode to edit. 

Tested on nightly 2022-12-15

**Comment by 86maylin** [comment]
[t2_119_pma_jacket__suit.zip](https://github.com/WolvenKit/WolvenKit/files/10254323/t2_119_pma_jacket__suit.zip)
On second thought maybe I should've included the glb, so here it is. Hope that helps.

**Comment by seberoth** [comment]
Tried to reproduce your error. Original submesh_01 is the "main" part of the jacket. If I import yours, its 00. So far so "good"^^

Opened your glb in blender and exported it again withou changes and now it imports back as the original in wkit (also the file is smaller?). Are there some settings (besides tangents) in blender I need to set?

**Comment by 86maylin** [comment]
This is my export settings(should be the settings recommended in the wiki): 
![image](https://user-images.githubusercontent.com/20621809/211253298-32f4b74b-9ca9-4acd-8cbe-0988f2e53ff7.png)
I've noticed that it's not really random, but it'll put the last submesh of the group you merged and separated to be the first one?

**Comment by Syrrr** [comment]
The reason this is caused can be seen when importing your GLB file.

If you look at this:
![image](https://user-images.githubusercontent.com/25871133/212485626-cdd9a29c-9601-4864-8074-13f2dc28128c.png)
The object is called submesh_01_LOD_1.002, but the actual Mesh Data related to it is called submesh_00_LOD_1.030.

The object submesh_00_LOD_1.001 in comparison contains Mesh Data submesh_00_LOD_1.031.
![image](https://user-images.githubusercontent.com/25871133/212485686-2f548d17-ad1d-4de4-9eb4-c88a99678c02.png)


Which is why it gets reordered by WKit.
