### ISSUE TITLE
Import+Export tools: display settings and persistence

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1040]
**Describe the bug**
Upon first launch of Wkit, the new import and export tools aren't initially displayed like the Import/Export tool used to be. 

"View -> Save Layout to Project" doesn't consider positions of import or export tool.

**To Reproduce**
1. Open WKit. See no import or export tool.
2. Under "Tools", add both of them to visibility
3. Move them in place on the GUI (I like them in the same place as the previous tool was, on the right-hand sidebar)
4. Save layout to project
5. close WKit
6. reopen WKit
7. behold the lack of visible import or export tool

 - Win64, WolvenKit-8.8.1-nightly.2022-12-20

**Comment by V3sn4** [comment]
+1 After docking and closing the window, it pops up again as a separate one instead of being docked like it used to be by turning the view off and on. 

No switch between import/export makes 2 additional windows to care about instead of a quick change between the two. It creates way more clutter on screen.

**Comment by rfuzzo** [comment]
fixed in #19f4cd2473de2ed64c460c7eb37e44ea4ea6089e
