### ISSUE TITLE
Automatic exception reporting

### ISSUE THREAD

**Issue by philippTheCat** [WolvenKit/WolvenKit#107]
- would automatically send exceptions to a central server
- needs to be _opt in_ (to comply with laws and fuck opt-out)

- possible library sentry / raven-csharp

**Comment by Traderain** [comment]
I think as a start simoly subscribing to unhadledexception and sending everything will be sufficient. Probably a tickbox where you select wcc_lite and such will do for settings as well.

**Comment by philippTheCat** [comment]
if we go with sentry we'd need to figure out if we're gonna self host and maintain that server, or if hosted is sufficient (free plan only has 1 user and only 7 days retention, small plan is $26 with unlimited users and 90 days retention)

**Comment by Traderain** [comment]
So my idea is basically:
- I will setup https://github.com/getsentry/raven-csharp on my webserver.
- We add a messagebox on the first run if someone wants to opt in.

As a first run handle everything unhandled:
- https://stackoverflow.com/questions/5762526/how-can-i-make-something-that-catches-all-unhandled-exceptions-in-a-winforms-a
and report it. Also sending the project file? or something maybe only the file list?

**Comment by Traderain** [comment]
Did a basic setup:
![image](https://user-images.githubusercontent.com/6411732/45750930-f9212e00-bc10-11e8-8fd1-d14512029dc8.png)
Seems to be working okay.
It needs to be decided what to report and what not. Since some files simply generate a bunch of exceptions but don't actually break the file so asking the user for comments and such may not be a great idea because it could get annoying.
