### ISSUE TITLE
Ability to change default mod directory

### ISSUE THREAD

**Issue by shamowfski** [WolvenKit/WolvenKit#1379]
**Is your feature request related to a problem? Please describe.**
I keep the mods I make on a different drive.  Every time I create a new mod I have to select the correct directory.  It would be nice to be able to change the default from "C:\Users\myuser\Documents"

**Describe the solution you'd like**
In the settings where you can change the cyberpunk exe path, the depot path, add a field for 'default mod directory' path.

**Comment by DoctorPresto** [comment]
there's the ability already to specify a secondary mod folder. which can be used for investigation other mods The default mod directory is based on your exe location because that's where the mods need to be for the game to load them.

![image](https://github.com/WolvenKit/WolvenKit/assets/111536029/2ba8e202-57cf-4bcf-b5d2-cb0b791f325b)

**Comment by shamowfski** [comment]
I'm referring to this field in particular.  It shouldn't matter where the unpacked mod files are stored.  

![image](https://github.com/WolvenKit/WolvenKit/assets/10904002/d1ff85f4-f37d-4820-9ea9-a2bf0ac90d8d)

**Comment by DoctorPresto** [comment]
I'm with you on this one, but https://github.com/WolvenKit/WolvenKit/issues/1154

**Comment by shamowfski** [comment]
Ah.  Thanks.
