### ISSUE TITLE
Vehicle .anim files corrupted when import

### ISSUE THREAD

**Issue by MetaMekaGnome** [WolvenKit/WolvenKit#1403]
**Describe the bug**
When an `.anim`  is imported from a `.glb` file, the structure is modified, causing some "animation explosion" ingame, then it freezes and crash.

**To Reproduce**
1. Add a vehicle `.anim` file from asset explorer into the project
2. Export the file as `.glb`
3. Import back the unmodified generated `.glb` into `.anim` file
4. Install and Launch the game
5. Interact with vehicle

**Expected behavior**
The file should have the same structure, but it's altered in a way by Wolvenkit.

**Version:**
 - Version 8.11.1-nightly.2023-10-23

**Info**
To compare the modifications, I have added two files: 
 - The original vanilla `.glb` file exported from vanilla `.anim`
 - The altered `.glb` exported from the imported altered `.anim`

You can already notice a file size difference between the two.

Note from Doctor Presto:
> When I was home I compared the glbs, wkit is adding an extra entry to animdatachunks. numAnimKeys and numConstAnimKeys are 0, numAnimKeysRaw is substantially higher and is higher than those values added no idea what unkIndex or zeInBytes but they're all wildly different, isScaleConstant is changed from 1 to 0, and it's not counting the buffers properly 
the unkIndex  thing I think is the issue - when it's writing back, it's counting as though that was a buffer
so intead of buffer 1 - unkIndex 1, buffer 2, buffer 3 it's going buffer 1 - unkIndex 2, buffer 3, buffer 4

**Screenshots**

https://github.com/WolvenKit/WolvenKit/assets/29430316/d056d17f-6e26-4ebb-af48-446097d0b941

**Files to compare**

*`.glb`*
[ANIMATIONS_v_sport2_mizutani_shion.zip](https://github.com/WolvenKit/WolvenKit/files/13182926/ANIMATIONS_v_sport2_mizutani_shion.zip)

*`.anim`*
[ANIM_v_sport2_mizutani_shion.zip](https://github.com/WolvenKit/WolvenKit/files/13198439/ANIM_v_sport2_mizutani_shion.zip)

**Comment by seberoth** [comment]
Anims have changed since 2.0.
ConstAnimKeys (numConstAnimKeys) was not used before (at least not in wkit) but was causing issues now. I just added them to reading without looking what they do (so that at least they export again)
But since I don't know how anims work I can't really fix anything else with it. Also we currently have no one who knows...

**Comment by effs** [comment]
There's a lot that's different, it seems, including tracks - we do seem to read tracks elsewhere though, so it might be something else throwing it off there.

The buffer changes shouldn't be an issue in that it does refer to the correct buffer (I think), wkit just splits each animation into its own buffer (`UnkIndex`) instead of offsetting it in the single one (`FsetInBytes`) while the data width (`ZeInBytes`) remains the same.

Interestingly enough there does seem to be a kinda bug in that the original buffer is never cleared but that's just a waste of space and a +1 to the animset index but that's set correctly.

If somebody knows what the animkeys and tracks correspond to in GLTF or at least Blender, that'd be helpful. Otherwise I'll try and muddle through figuring out what the right fix is.

**Comment by rfuzzo** [comment]
Loomy said he'd be willing to help. But yeah we don't have anyone to support glb-anims. All I can support is importing with redmod in wkit.

**Comment by effs** [comment]
:shruggies: How hard could it be

**Comment by rfuzzo** [comment]
yeah, "animations are just numbers anyway" right? :D

**Comment by effs** [comment]
Correct, it's just manipulation of data in structures.

**Comment by effs** [comment]
Doesn't look like this was working in 1.63 either. I dunno if it's arguably less broken in 1.63, but if so, not by much.

Which is not to say wontfix, but this'll be a bigger job than 'just' fixing the difference between 1.63 and 2.0.

![image](https://github.com/WolvenKit/WolvenKit/assets/13802421/25880ed3-3355-4a5e-bc8c-0f0b3a1c855b)

**Comment by MetaMekaGnome** [comment]
Thank you all, for your time and work on this issue :)
