### ISSUE TITLE
Potential archive packing issue

### ISSUE THREAD

**Issue by AllKnowingLion** [WolvenKit/WolvenKit#1509]
**Describe the bug**
While working on the 3.0 update for the UV Framework, we noticed that our generic overlay tattoo textures were not appearing in game. We have a version that functions dated December 15th 2023, then the next iteration from the 17th does not display the overlays. It WILL however, display the emissive overlays.

In and of itself, this sounds like user error on my/our part. HOWEVER, when we pack the exact same archive with CP77 Tools (wolvenkitcli_1.8.2) the overlays come through.

I am guessing this may be due to there at one point having been a capitalized folder name in the filepath, but now when unbundling, it doesn't seem to be present, and furthermore, if that were the case, it should also affect the emissive textures, yet they still come through.

**To Reproduce**
Pack and install UV Framework 3.0 (and possibly earlier iterations) with any wolvenkit nightly dated 12-15-23 or later.
Have any UV-Compatible overlay tattoo in your mod folder (ordered *above* the framework)

If the tattoo texture does not come through, then repack the archive using the CP77 Tools v1.8.2, and the desired tattoo should then come through.

**Expected behavior**
The tattoo texture should be displayed on the player body, however, if this is replicable for the tester as it was for myself and the two others working on it at the time, then emissive tattoos should be displayed, but the generic ones would not

**Version (please complete the following information):**
possibly version either [8.11.2-nightly.2023-12-16] or [8.11.2-nightly.2023-12-15] 

**Screenshots**
N/A

**Comment by seberoth** [comment]
The problem was that we fixed a bug, which prevented the archive writer to write resourceDependencies to the packed file (just like CDPR does it). This bug was caused due to me changing some methods a while ago.

But we didn't know that this "fix" would prevent loading of these dependencies when they are overwritten in another archive file. The list forces the game to take the file in the same archive.

For example: `yourModA.archive` has a file called `something.mesh` which uses `something.xbm` and another mod (loaded after yours) is replacing `something.xbm`, that other file wouldn't be loaded.

So my fix to the writer made things worse for mods like yours...
