### ISSUE TITLE
Better error message for GPU-driver related crash

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1522]
I often run into this error when Blender crashes my graphics driver. Usually, a restart of Wolvenkit fixes the problem:
![image](https://github.com/WolvenKit/WolvenKit/assets/965785/34caacc7-1686-46c6-a428-42883053bbec)

It would be good to give the user a human-readable error message, e.g. "Your GPU driver crashed. Please restart Wolvenkit"

**Comment by abheekda1** [comment]
I think this is where the error is being printed out:
https://github.com/WolvenKit/WolvenKit/blob/8882f65af122250b7b15f1baa016f4d759cb5725/WolvenKit.App/ViewModels/Importers/ImportViewModel.cs#L255-L259

Could you add a line to print out the type of exception? That way I believe it will be possible to add a specific check in the exception to print out a specific error message. To get the type of exception would you be able to add like `_loggerService.Info(e.GetType().Name)`?

If someone else knows more about the graphics/DirectX please say something because I know nothing about that actual API interaction.

**Comment by manavortex** [comment]
That's a good idea, actually. I'll need to test something else, but I'll try to remember :/

**Comment by manavortex** [comment]
```
[1/31/2024 6:19:42 PM] [Error    ] Exception type: System.Runtime.InteropServices.COMException
[1/31/2024 6:19:42 PM] [Error    ] Exception type: COMException
```

**Comment by seberoth** [comment]
Should be better now with a3490b9

```
[Warning] Error while getting GPU instance. Reason: HRESULT = 0x887A0007. Retrying...
```

and if it fails multiple times
```
[Warning] Error while getting GPU instance. Reason: HRESULT = 0x887A0007
[Warning] Fallback to software compression. Please try restarting WolvenKit to fix this issue.
```

Also should switch back to software compression now if it fails to get a handle from the gpu

**Comment by manavortex** [comment]
You're a legend, Seb. <3
