### ISSUE TITLE
Textures are not converted when exporting character entity

### ISSUE THREAD

**Issue by Tosyk** [WolvenKit/WolvenKit#1542]
**Describe the bug**
After partial depot and importing a character entity into the empty project. When I export character entity from project to my SSD with `export_ent` script, I get not textures converted.

**To Reproduce**
1. Import any character entity into the project mod (e.g. jackie_welles.ent)
2. Click it twice in the project to activate
3. Export it with Tools -> Script Manager -> `export_ent` script
4. Import into Blender (I tried with version 3.6), and you will notice that no textures have been loaded.
5. also, if you will look for the png you will only find xbm

**Expected behavior**
Textures of exported character entity are converted into png/dds/tga or anything to work with but not xbm

**Version (please complete the following information):**
 - Version 8.12.1

**Screenshots**
![image](https://github.com/WolvenKit/WolvenKit/assets/24209966/f8f29c4a-e691-4936-8f39-6d1be9cdff01)
<img width="692" alt="image" src="https://github.com/WolvenKit/WolvenKit/assets/24209966/809235d6-6c9c-4b99-b0b5-3c3a4cb0fca1">

**Comment by DoctorPresto** [comment]
can you confirm that you have set a depot path in your wolvenkit settings 
![image](https://github.com/WolvenKit/WolvenKit/assets/111536029/6dd47158-dd12-4116-8474-7d7326c5b8a9)
Next question is which version of the blender plugin you're using? I can't replicate any issues at all with Jackies ent.

![image](https://github.com/WolvenKit/WolvenKit/assets/111536029/d081672d-6311-4c9a-9cfa-78e36b3e7a52)

Also - you're in the archive directory of your project folder. If you look at the path, change the word archive to raw and you'll see the pngs though they're likely not what you're expecting them to be.

**Comment by Tosyk** [comment]
Depot is set.
![image](https://github.com/WolvenKit/WolvenKit/assets/24209966/d9034a58-e509-43b5-9fa5-f7481cc1c807)
as been said I completed partial depot extraction to the depot directory which is not 111gb

I'm using latest version of everything, wolvenkit, blender plugin. Only the blender is 3.6.

Also, I'm not sure what are you talking about when you say I'm in archive directory, because I'm not really choosing any directory to be in :) I'm following this tutorial https://wiki.redmodding.org/wolvenkit/modding-community/exporting-to-blender

**Comment by DoctorPresto** [comment]
Cyberpunk textures aren't normal PBR textures which would be labelled/useful in the way you're suggesting. What happens on export is that wkit creates a material.json which instructs the blender plugin on how to recreate the cyberpunk shaders. 

Your setup looks correct on the wkit side so blender import should be working. Just as an experiment, could you try changing the depot path you've set in wkit and re exporting all the meshes? Just add the number 1 or something to the depot path in wolvenkit, go to the export tool and press export all. Then try reimporting the entity into blender
. 
If that doesn't work, please reach out to me on discord, your issue is extremely unlikely to be a wkit error and it'll be easier to troubleshoot in real time. 

Also, don't worry at all about doing a new partial depot extraction as it's not necessary for what you're doing.

**Comment by Tosyk** [comment]
accidentaly closed issue. reopened *silly*

**Comment by Tosyk** [comment]
suggested solution is not working tho
![image](https://github.com/WolvenKit/WolvenKit/assets/24209966/a334b7b4-4c70-4c79-ac0d-54f768ce9083)

**Comment by Tosyk** [comment]
sent a message in discord

**Comment by Tosyk** [comment]
after the fix everything is working out of the box and according to the guide
![image](https://github.com/WolvenKit/WolvenKit/assets/24209966/bffc84f0-9115-466e-8f42-60cdda0c1571)
