### ISSUE TITLE
Welcome page aditions

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#161]
So when you open wolvenkit having a couple neat tutorials would be nice and making our workflow easy for those who just want to make a simple mod would be neat:  
- [x] Script modding tutorial. Video making a simple exec script will do. @Traderain 
- [ ] Texture modding tutorial. Replacing and adding new. @rfuzzo 
- [x] Sound modding tutorial. Replacing and adding new. @Traderain 
- [ ] Speech modding tutorial. Replacing and adding new.  @Traderain 
- [ ] String modding tutorial. Replacing and adding new. @Traderain 
- [ ] 3d modding tutorial (anims, rigs models)  Replacing and adding new. @vonLeebpl 

Once this is working and we have the basic tutorials WolvenKit 1.0 should be released!

**Comment by Maxzor** [comment]
Hello, any progress updates on various tasks? I'm eagerly waiting for most of them :)

**Comment by ja-to** [comment]
Proposition for welcome page on next release:

I don't think we should record long-form specific tutorials as individual links. Instead I'd be happy to record one longer introduction video to WolvenKit. A little bit of introduction to the application itself, but mostly for existing users. I'd like to demonstrate the all-in-one functionality (no more extra programs like w3oven), briefly overview some tools, and explain the new build pipeline which can handle cooked files in the background.

Recording long-form video tutorials is such a pain, because in the span of a week WolvenKit can look completely different and several hours of work goes down the drain. I suggest we link the following:

Introduction video to 0.7 series
WolvenKit Github Repository
WolvenKit Wiki which hosts tutorial-like content in both video and written form

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)

**Comment by ja-to** [comment]
I believe we can close this issue.

I don't think anybody is going to spend a huge amount of time documenting Legacy WolvenKit. And for next-gen WolvenKit we are focusing primarily on wiki-style documentation instead of guides or tutorials.

We could create a separate issue specifically calling for help with the wiki documentation, but I don't know if that's completely necessary.
