### ISSUE TITLE
Unable to open, re-open, or close Project Explorer through View

### ISSUE THREAD

**Issue by ArasakaApart** [WolvenKit/WolvenKit#1872]
**Describe the bug**
Unable to re-open the Project Explorer frame when it is closed. It also doesn't close the frame when it is clicked on in the View options.

**To Reproduce**
1. Click on "Open Editor"
2. Click on "View"
3. Click on "Project Explorer"

**Expected behavior**
I expect the Project Explorer to open again when it is called upon.

**Version (please complete the following information):**
 - 8.14.1-nightly.2024-07-30

**Media**
https://github.com/user-attachments/assets/0b0b2f8f-567d-4267-9bcc-c0caa6759f69

**Comment by seberoth** [comment]
The issue was introduced with https://github.com/WolvenKit/WolvenKit/commit/c8564837aa6b954b59fb5793ba14eb25a48fdb88#diff-dc5060e56ec0447f1256cf4f88264e55a1c4d1aacad126f5568b7e16eca13448R1202

Overwriting `OnPropertyChanged` without calling `base.OnPropertyChanged` will interrupt the event chain and the listener which manages the visibility of the tool window isn't called
