### ISSUE TITLE
Option to copy appearance name when right clicking on one in the CMesh view

### ISSUE THREAD

**Issue by ArcadieCalliope** [WolvenKit/WolvenKit#1894]
Essentially, just as the topic title says. If possible, having the option to copy a mesh's appearance name when you right-click (or right-click+holding shift) would be a convenient time saver. To ensure I am clear, I am only referring to the text of the name itself. I understand you can't just copy info from a .mesh to paste into a .app file. 

Appreciate y'all!

![Screenshot 2024-08-12 195733](https://github.com/user-attachments/assets/4b1ec0c4-4f79-4314-a512-e56c588b0cf5)

**Comment by manavortex** [comment]
I usually click on the record and then grab the name from the panel at the side:

![image](https://github.com/user-attachments/assets/08986c2d-c994-4416-8ddf-96a29b1ca8dc)

I could add a context menu item to copy that, but I'm a little hesitant because it's exactly as many clicks as doing it via panel (okay, you save the ctrl+A, ctrl+C). Does that make your issue go away? 
Otherwise, I'd implement it for anything with a description and/or value :)

**Comment by ArcadieCalliope** [comment]
Absolutely solves my issue in wkit... but it made the issue that I'm a big dummy sometimes waaay more apparent haha. Thank you!!
