### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by penktadienis13** [WolvenKit/WolvenKit#1950]
**Describe the bug**
[Error    ] Message: Object reference not set to an instance of an object.
Source: WolvenKit.Modkit
StackTrace:    at WolvenKit.Modkit.RED4.ModTools.ImportMesh(FileInfo inGltfFile, Stream inMeshStream, GltfImportArgs args)
   at WolvenKit.Modkit.RED4.ModTools.ImportGltf(RedRelativePath rawRelative, DirectoryInfo outDir, GltfImportArgs args)
Error    ] The following items failed:
C:\path-to-glb\phgr.glb
[phgr.zip](https://github.com/user-attachments/files/17227743/phgr.zip)

**Comment by kmirea** [comment]
not enough info to give a meaningful diagnosis, but one potential cause of reimport issues is the re part... when importing a glb mesh./anim, it looks for the corresponding named .mesh/.anim within your project -  it updates / overrwrites the original.  if the glb is not from some existing file in ur project, or u change the filename or path, then it will fail in some cases to find the target to import over.   However try share the specific line number reference in log, or give complete log - to narrow it down to actual cause, cant do anything with GLB because of aforementioned issue. what is the original depot path of the file u editing/overwriting ?  If its a totally new asset, not in the game or project then the approach would be to duplicate a random mesh file, rename and relocate it within ur project to match name/path of glb in ur raw folder, .

Another potential issue is missing / excluded / not previously existing things like materials, or bones (whether mesh bones or within the associated rig file (if there is one in this case) - cant reallky help on the former, but in so far as bones go, u need to first edit the original mesh within project and rig if necessary |(within wolvenkit) and add any new bones (or easiest is clone an existing one and all associated properties (transforms, parenting, etc|).  Then only can u export that modifed file to GLB|/blender, and be able to reimport it afterward, without any errors.  knowing what actual line the error is triggered would give better idea though
