### ISSUE TITLE
.w2l holds texture maps in texture.cache, not properly handled by wkit

### ISSUE THREAD

**Issue by Maxzor** [WolvenKit/WolvenKit#203]
**Describe the bug**
w2l correspond to CLayer class.

There are multiple entries in the cache with the same file name. They correspond to different texture map types : specular, displacement, glossy, normal, ...idk
![image](https://user-images.githubusercontent.com/16599683/89519977-7e9a3100-d7dd-11ea-9e3c-3e29669bcdcf.png)

On import wkit identifies them as duplicates and you can select only one
![image](https://user-images.githubusercontent.com/16599683/89520375-0b44ef00-d7de-11ea-9c3e-c692699e9132.png)

They are not assembled as mipmaps(.w2cube) are because they have no mipmap index.
In  DLC\bob\content\texture.cache [w2l.xlsx](https://github.com/Traderain/Wolven-kit/files/5034172/w2l.xlsx)

**goal**
Find a way to (assemble better the mipmaps, ) deal with those w2l without IWitcherFile duplicates, possibly with surrogate class.

**Comment by rfuzzo** [comment]
hmm, I'm not sure the terminology is correct here.

First, mipmaps have nothing to do with w2cube. A cubic texture consists of 6 faces (a cube), each of which can have itself  mipmaps. e.g a normal 2D texture might have 11 mipmaps (around 8 of them are usually in the texture cache, the smallest are skipped). a cubic texture (w2cube) has 6 faces, each of which has again, say, 9 mipmaps. that makes in total a maximum of 6x9 (usually lower) offset count which has to be assembled.

Second, the w2l files in the texture cache have nothing to do with the CLayer class. (I don't know why CDPR put w2l files into texture cache...) but these are just normal textures. 

Third, I believe these are duplicated because CDPR put multiple files with the same name into the cache? although I am not sure about this...

**Comment by Maxzor** [comment]
[w2l.xlsx](https://github.com/Traderain/Wolven-kit/files/5035842/w2l.xlsx)

**Comment by Maxzor** [comment]
I tried getting a ground truth today from wcc_lite splitcache without success.
Got loads of "Split list file required errors".
Will try to document my micro research in one week.
Anybody having managed to do this is welcome to input his results here!
