### ISSUE TITLE
help me,I can't download these files anyway.....

### ISSUE THREAD

**Issue by jike1Wang** [WolvenKit/WolvenKit#2084]
![1734359156299](https://github.com/user-attachments/assets/6f3aa6a4-07b0-40e9-a8e3-1517dfdeeca6)
# Issue template
Overview of functionality you wish to be implemented or fixed in software.

## Steps to reproduce
Steps required to reproduce bug or test that functionality is implemented.

## Actual Result
A description of what actually happened.

## Expected result
A description of what you expected to happen.

**Comment by manavortex** [comment]
That's what happens when Wolvenkit can't reach the server to download the files from. The bad news is, we don't know how to fix it.

The good news is, you can install everything by hand:
- CET: just install Cyber Engine Tweaks
- MLSetupBuilder: [wiki has instructions](https://wiki.redmodding.org/cyberpunk-2077-modding/for-mod-creators/modding-tools/mlsetup-builder)
- WolvenkitResources: This is supposed to update the system scripts. You can download [this github repository](https://github.com/WolvenKit/Wolvenkit-Resources/), then copy the folder `Scripts` to your Wolvenkit install directory, subfolder `Resources` (there already is a script folder, you need to merge them, and overwrite any files)
