### ISSUE TITLE
Metadata.store parser

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#33]
We need a way to parse&write metadata.store files so we don't have to use wcc_lite for it which is slow
- [x] Parser
- [ ] Writer

**Comment by Murzinio** [comment]
Ok, so that's known so far (maybe inaccurate but I will write all I'm pretty sure about):

**Header block**, the first 16 bytes are pretty straightforward.
int32 header;
int32 version
int32 biggestFileSizeCompressed;
int32 biggestFileSize;

**Paths block:**
First byte/bytes are the length of the paths block counting from this byte. Example:

`1700626C6F62302E62756E646C6500615C610000610061`

Which in clear text is:
`..blob0.bundle.a\a..a.a`

First byte is the length, and here starts some magic. Up to 0x39/0x40 it's just plainly written, after that another byte appears, and the pattern it's something like 
`byte2 = (finalLength - (byte1 - 63)) / 64;`

Something similar is used for the fileSize above.
The longer the paths are the more complicated it gets with more bytes, I guess it needs to be figured out with the debugger.

After that comes a null byte. Then there is the bundle path ("blob0.bundle")

And remaining stuff, which appears to be sorted alphabetically:

All the files paths.
Null byte
All the files and folders separated with null bytes.
Paths block ends with another null byte and a file count (that is actually file count incremented by 1, so it's 02 for 1 file, 0x21 for 32 files etc)

After that there are **32 null bytes**.

Then the file records blocks start:
**File record block 1** is:

For each file:
int32 filePathLength - it's counted like in the example above, so for the first file in that case it's `0E 00 00 00`
4 nullBytes;
int32 fileSizeCompressed;
int32 fileSize;
int32 fileIndex;
int32 compressionAlgorithm:
8 null bytes;
int32 lastIndex // last file index + 1

Ends with **16 null bytes**;

Then there are another 2-3 file records blocks with something that appears to be bundle count/index, some magic related to the files count, file paths hashes for each file (fnv1a64 iirc), and stuff I have absolutely no idea about so far. Looking at the exe map it's probably that stuff that's missing:

GetBundleInfo, GetFileAccessInfo, GetFilesInBundle, GetFileAccessInfos, GetBufferFileID

**Comment by Traderain** [comment]
Impelemted most stuff: https://gist.github.com/Traderain/08df5788e9cc870ab07d26bbb9f61a7a

**Comment by Traderain** [comment]
Parser implemented properly now.
![image](https://user-images.githubusercontent.com/6411732/44406875-00dfab00-a55d-11e8-810a-62ac3333b5bc.png)
Reads game metadata properly.

**Comment by Traderain** [comment]
I figured out that we could use this to "cache" bundles later down the road which would make loading stuff insanely faster. But this is a prio c thing.
