### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#331]
For newcomers and generally for improving our workflow the project should be better documented:
- [ ] xmldoc comments
- [ ] A getting started page
- [ ] A description of how the project is structured and such
- [ ] A proper coding style md file

**Comment by simon-brooke** [comment]
A getting started page would certainly be helpful; for folk who aren't familiar with Doxygen it would probably be good to link to the download page in the README and explain how to load the doxygen.conf file into doxywizard. It's also worth saying that on a project as big as this doxygen doesn't run very quickly; it might be a good idea to add the `docs` directory to the repo so that it can be auto-published to `https://wolvenkit.github.io/wolvenkit/`.

So far I've had to install VS2019 and Doxygen, and I've chosen to install GitKraken; I'll add any other tools I have to install (this is my games machine so it hasn't have dev tools on it before).

I haven't got the documentation built yet (doxygen is still running) but browsing the source code the commenting looks reasonably good by the standards of open source projects generally.

Would you accept a pull request for either an updated `README.md` file or a separate `BUILDING.md` once I've got everything working?

**Comment by Traderain** [comment]
Sure, we have rencetly updated the readme in the dev branch so check it out
but if you have any enhamcements, feel free.

**Comment by Offline-R503B** [comment]
I have made a Wiki instead regarding 

>  A getting started page
>  A description of how the project is structured and such
>  A proper coding style md file

**A few things needed to progress.**
- [ ]  Clean up all code. (Already started with this in general.)
- [ ]  Document services etc on the wiki and how to use them so we dont get duplicate code.
- [ ]  Comments for Single line functions or full functions. So one can read from the comments what is going on. App.xaml.cs will be the primary example to follow on this format.
