### ISSUE TITLE
CR2W editor UI

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#457]
Fixing the cr2w editor design (DocumentView.xaml)

~~- [ ] editing on single click - right now you need to click inside a row AND THEN you can edit it. instead you need to be able to edit with only one click~~
- [x] Textboxes etc are too big for their rows (has to do with handy controls resizing)

![image](https://user-images.githubusercontent.com/37657287/118094037-84591e80-b3ce-11eb-8f11-52e6d3fa4efa.png)

**Comment by rfuzzo** [comment]
- [ ] revamp the chunk/imports/buffers view somehow (at least resize the expander)

**Comment by Offline-R503B** [comment]
1 : Isn't this expected behavior for a excel like editing thing? 

2 : 
![image](https://user-images.githubusercontent.com/11785451/118119816-3c96bf00-b3ef-11eb-86b7-188e4f791cfe.png)

I fixed the comboboxes + checkboxes + textboxes 👍 


3: 
![image](https://user-images.githubusercontent.com/11785451/118119956-736cd500-b3ef-11eb-8211-90312559c942.png)

1 : Is to resize it back to "hidden" .
2 : sizes to the width of the items.

**Comment by rfuzzo** [comment]
# ENHANCEMENTS
* imports  sidebar-> click on import to import the import
* click on a chunk handle and move to said chunk in the editor
* add/remove array elements
* copy chunks
* add chunks

# FUTURE PROJECTS
- buffers sidebar-> open buffer editor
- add a node-graph editor for chunks
