### ISSUE TITLE
Unit tests in CI

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#494]
- [ ] Potentially host a server somewhere with both game's files and run the unit tests for dev commits. I don't know the legal part of this etc. but would be neat to self-host github actions anyway

**Comment by gammaparticle** [comment]
From the CP2077 EULA (via Steam: [https://store.steampowered.com/eula/1091500_eula_0]):

3.1	Licence. CD PROJEKT RED gives you a personal, limited, revocable, non-exclusive, non-transferable and non-assignable licence to display, view, download, install, play and use Cyberpunk 2077 on your personal computer, games console and/or other devices/platforms that are explicitly authorised by CD PROJEKT RED (the list of which is available here [https://www.cyberpunk.net/]), depending on the particular device/system/platform you purchased the game for. This licence is for your personal use only (so you cannot give, ‘sell’, lend, gift, assign, sub-license or otherwise transfer it to someone else) and does not give you any ownership rights in Cyberpunk 2077.

Based on the above, one could self-host github actions on a **personal** computer (at one's home) that contains a single copy of the CP2077 game files, ensuring security precautions (i.e. on its own separate VLAN and filtering ingress traffic).  This setup would theoretically avoid violating CDPR's license instead of copying game files to a commercial hosting/cloud service which may violate the license as hosting service's VMs and VPS' are not considered your 'personal computer'.

This would mean a volunteer could set this up/configure on their home network. 
Don't know if this strategy has been discussed...

**Comment by WopsS** [comment]
That's a good idea if we want to do that, but should be kept in mind that it might take hours to complete and might pose a security risk according to [GitHub docs](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories).

```
We recommend that you only use self-hosted runners with private repositories. This is because forks of your repository can potentially run dangerous code on your self-hosted runner machine by creating a pull request that executes the code in a workflow.
...
```

Another option to this is to create a separate executable that is used to validate WolvenKit output with game's archives, if there is a mismatch then a unit test is added for the expected bytes (similar to TweakDB module). That way we only have to run the unit tests on GitHub, and once in a while we run the executable when the archive format change or someone reports a problem with an archive.

**Comment by Traderain** [comment]
How about a bot? You comment somewhere !test and a bot pulls it and runs the tests but just the tests.

**Comment by WopsS** [comment]
That would be interesting, might be as a commit message or a Discord message 🤔
